### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by GuruVirus** [zxix/stable-diffusion-pickle-scanner#6]
So I have WebUI installed, but I don't have a GPU so I can't run webui (at least with my current commandline args; cpu mode not enabled). I'm getting this when running inside base SD folder or outside of it.
![image](https://user-images.githubusercontent.com/4285187/202070346-c70496e0-8c4e-4473-b999-e325b62bc4a4.png)

**Comment by bluekght** [comment]
Same

**Comment by Ruffy314** [comment]
Can you give more information about your system and environment?
I have installed python 3.10.6,  AUTOMATIC1111's web UI and this pickle-scanner on a Windows 10 laptop without GPU, and I cannot reproduce the error.
Stable Diffusion 1.4 checkpoint passes the scan, ykilcher's totally-harmless-model fails the scan as expected.

@GuruVirus it looks like you use your normal python environment instead of the venv from the web UI. Maybe you have the wrong version of some python library? Could you try replacing the command *python* with your venv path? It should be in the first line of  the console window when you start up AUTOMATC1111's web UI. For example, if the line said 
`venv "E:\ai\stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe"`
your command to start the pickle scanner would change from `python pickle_scan.py models 1 > scan.txt` to `"E:\ai\stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe" pickle_scan.py models 1 > scan.txt`

**Comment by GuruVirus** [comment]
WebUI doesn't load for me, but the venv path worked like:
`"E:\ai\stable-diffusion\stable-diffusion-webui\venv\Scripts\Python.exe" pickle_scan.py models 1 > scan.txt`
